---
# Setup for all the master
#
- name: Sanity sleep
  pause: seconds=60

- name: Reset existing k8s
  shell: "kubeadm reset"
  register: reset_cluster

- name: Set master ip address 
  set_fact: 
    master_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: Init kubeadm 
  when: reset_cluster|succeeded
  shell: |
          kubeadm init --token {{ token }} --apiserver-advertise-address= {{ master_ip }} --service-cidr= {{ service_cidr }} \
          --pod-networ-cidr= {{ pod_network_cidr }}
  register: init_cluster

- name: Create k8s config directory
  file: path="$HOME/.kube" state=directory

- name: Copy admin.conf to home directory
  when: init_cluster
  copy:
    src: "{{ kubeadmin_config }}"
    dest: "~/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
    remote_src: True
