---
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent 

- name: Disable swapfile 
  command: swapoff -a

- name: Delete swapfile 
  file: 
    name: /swapfile
    state: absent

#- name: setenforce 0
#  command: setenforce 0

- name: Remove chrony service
  yum:
    name: chrony
    state: absent
    
- name: Install ntpd service
  yum:
    name: ntp
    state: present
    
- name: Stop  ntpd service
  service:
    name: ntpd
    state: stopped
    
- name: Sync time service
  command: ntpd -gq
    
- name: Start  ntpd service
  service:
    name: ntpd
    state: restarted
    enabled: yes

- name: Firewalled is disabled  
  systemd:
    name: firewalld
    enabled: no

- name: Firewalled is stopped  
  systemd:
    name: firewalld
    state: stopped

- name: Change sysctl settings
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict: '{{ sysctl_config }}'

- name: Add modprobe br_netfilter
  command: modprobe br_netfilter

- name: Install epel-release package
  yum:
    name: epel-release
    state: present

- name: Set selinux to disabled
  selinux:
    policy=targeted
    state=disabled
  register: selinux_state_disabled

- name: Schedule system reboot
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: selinux_state_disabled.changed

- name: Wait for the reboot to complete if selinux is changed
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: selinux_state_disabled.changed
