---

- name: Create tmp dir
  file: 
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755

- name: Check if Helm is installed 
  shell: command -v helm > /dev/null 2>&1
  register: helm_exists_res
  ignore_errors: yes

- name: Install Helm if does not exists 
  block:
    - name: Get helm installer
      get_url: 
        url: "{{ helm_3_url }}"
        dest: "{{ tmp_dir }}/get_helm.sh"
        mode: 0755

    - name: Run helm installer
      shell: "{{ tmp_dir }}/get_helm.sh"

  when: helm_exists.rc > 0 

- name: Copy RBAC config file
  copy:
    src: rbac-config.yml
    dest: "{{ tmp_dir }}/rbac-config.yml"
    mode: 0644

- name: Kubectl apply  RBAC config file
  shell: kubectl apply -f "{{ tmp_dir }}/rbac-config.yml"

- name: Helm Init 
  shell: helm init --service-account tiller 

- name: Update Helm Repo 
  shell: helm repo update
