---
#This playbook deploys contrail+k8s 

- name: Install all the pre-requisties on cluster nodes to deploy k8s
  hosts: cluster
  become: true
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python
  vars_files:
    - vagrant.yml
  roles:
    - common
    - { role: docker, when: container_engine == 'docker' }
    - { role: containerd, when: container_engine == 'containerd' }
    - { role: rkt, when: container_engine == 'rkt' }
    - { role: kubernetes, when: deploy_k8s }
    - { role: upgrade-kernel, when: upgrade_kernel }

- name: Kubeadm init on master, and start services 
  hosts: masters
  become: true
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python
  vars_files:
    - vagrant.yml
  roles:
    - { role: master, when: deploy_k8s }

- name: Join worker node and start services 
  hosts: workers
  become: true
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python
  vars_files:
    - vagrant.yml
  roles:
    - { role: worker, when: deploy_k8s }

#CNI and extras
- name: Install CNI and extras on master node
  hosts: masters
  #become: true
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python
  vars_files:
    - vagrant.yml
  roles:
    - { role: contrail-cni, when: install_contrail_cni }
    - { role: calico-cni, when: install_calico_cni }
    - { role: metallb, when: install_metallb }
    - { role: helm, when: install_helm }
    - { role: portainer, when: install_portainer }
