---
# Common setup for all the hosts
#
- name: Sanity sleep
  pause: seconds=60

- name: Disable security 
  selinux:
    state: disabled

- name: Install required tools and ntp
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
     - ntp
     - net-tools
     - curl
     - util-linux
     - wget
     - tcpdump

- name: Make sure ntpd is running
  service: name=ntpd state=started enabled=yes

- name: Disable swap
  command: swapoff -a

- name: Disable firewall service
  service: name=firewalld state=stopped enabled=no

- name: Load netfilter onto kernel
  modprobe:
    name: br_netfilter
    state: present

- name: Append bridge-iptables file
  command: "{{ item }}"
  with_items:
    - echo "1" > /proc/sys/net/ipv4/ip_forward
    - echo '1' >> /proc/sys/net/bridge/bridge-nf-call-iptables
    - sysctl --system

- name: Copy kuberenetes repo file
  copy: 
    src: "{{ role_path }}/files/kubernetes.repo"
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install docker and kubeadm
  yum:
    name: "{{ item }}"
  with_items:
     - docker-ce-18.06.1.ce-3.el7
     - kubeadm
     - kubectl

- name: Make sure docker is running
  service: name=docker state=started enabled=yes

- name: Make sure kubelet is running
  service: name=kubelet enabled=yes
