---

- name: common setup
  gather_facts: yes
  hosts: k8s-cluster
  serial: 10
  become: true
  roles:
    - { role: common }

- name: k8s master setup
  gather_facts: yes
  hosts: master
  become: true
  roles:
    - { role: master }

- name: k8s nodes setup
  gather_facts: yes
  hosts: nodes
  become: true
  roles:
    - { role: node }

- name: setup extras on k8s master
  gather_facts: yes
  hosts: master
  become: true
  roles:
     - { role: extras }

- name: setup calico as cni
  gather_facts: yes
  hosts: master
  become: true
  roles:
     - { role: cni }

